name: flutter_phone_number_field
description: International phone number field
version: 0.0.3
repository: https://github.com/S7-Works/flutter_phone_number_field.git
homepage: https://github.com/S7-Works/flutter_phone_number_field.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0
  phone_number: ^2.0.0
  country_pickers: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
